book/urls.py
from django.urls import path
from .views import (
    book_detail_view,
    delete_book_view,
    star_rating_view,
    add_book,
    update_book_function,
    delete_book_view,
)


app_name = 'book'

urlpatterns = [
    path('<int:pk>/', book_detail_view, name = 'detail'),
    path('rating', star_rating_view, name = 'rating'),
    path('add-book/', add_book, name = 'add-book'),
    path('update/<book>/', update_book_function, name = 'update'),
    path('delete/<book>/', delete_book_view, name = 'delete'),
    

]

chat/urls.py
from django.urls import path
from .views import (
    send_message_view,
    get_message_from_js,
    create_room,
    start_discuss,
    start_is_true_view,
    rooom,
    close_chat_view,

)


app_name = 'chat'

urlpatterns = [
    path('', send_message_view, name = 'chat'),
    path('message/', get_message_from_js, name = 'message'),
    path('create-room/', create_room, name = 'create-room'),
    path('start-discuss', start_discuss, name = 'start-discuss'),
    path('start_time/', start_is_true_view, name = 'start-time'),
    path('room/<room>', rooom, name = 'room'),
    path('close/<room_name>', close_chat_view, name = 'close'),





]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.urls import re_path as url

urlpatterns = [
    #url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),

    path('admin/', admin.site.urls),
    #url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),

    path('', include('personal.urls')),
    path('account/', include('account.urls')),
    path('my-account/', include('myaccount.urls')),
    path('notification/', include('notification.urls')),
    path('book/', include('book.urls')),
    path('likeordislike/', include('likeordislike.urls')),
    path('aboutbook/', include('aboutbook.urls')),
    path('comment/', include('comment.urls')),
    path('question/', include('question.urls')),
    path('chat/', include('chat.urls')),
    
    
]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    #urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

chat/models.py
from django.db import models
from account.models import Account
from book.models import Book

# Create your models here.





class ChatOnetoOne(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    sender = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='from_user')
    receiver = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='to_user')
    body = models.TextField()
    time = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)

    def __str__(self):
        return self.body





class DiscussBook(models.Model):
    owner = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='owner_of_disscus')
    book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name='book_for_disscus')
    user = models.ForeignKey(Account, on_delete=models.CASCADE, null=True, blank=True, related_name='sender_text')
    discussion_users = models.ManyToManyField(Account, related_name='all_users')
    when = models.DateTimeField(null=True, blank=True)
    updated = models.DateTimeField(auto_now=True)
    text = models.TextField(blank=True, null=True)
    is_ready = models.BooleanField(default=False) #when add time then is_ready will be True
    is_start = models.BooleanField(default=False) #when time is 0 the chat start


    
    class Meta:
        ordering = ['-updated']


    
    def __str__(self):
        return self.book.name






class ChatText(models.Model):
    room = models.ForeignKey(Book, on_delete=models.CASCADE)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text

chat/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from .models import ChatOnetoOne, DiscussBook, ChatText
from account.models import Account
from django.http import JsonResponse
from book.models import Book
from notification.models import Notification
import datetime
from aboutbook.models import Discuss

# Create your views here.



#close chat room

def close_chat_view(request, room_name):
    user = request.user
    room = DiscussBook.objects.get(book__name = room_name)

    if request.method == 'POST':
        discussbook = DiscussBook.objects.all().filter(book__name = room).delete()
        chat_text = ChatText.objects.all().filter(room__name = room).delete()
        discuss = Discuss.objects.filter(book__name = room).delete()
        noti_time = Notification.objects.filter(receiver = user, book__name = room, notification_types = 5).delete()
        noti_agree = Notification.objects.filter(receiver = user, book__name = room, notification_types = 4).delete()
        
        messages.success(request, 'Chat room succesfully closed!')
        return redirect('/')

    context = {
        'room': room
    }
    return render(request, 'chat/close.html', context)




#room

def rooom(request, room):
    room = DiscussBook.objects.get(book__name = room)
    book = Book.objects.get(name = room.book.name)

    texts = ChatText.objects.all().filter(room = book).order_by('-created')

    rooms = DiscussBook.objects.all().filter(book__name = room)

    user = request.user
    if user.is_authenticated:
        if request.method == 'POST':
            room = rooms[0]
            text = request.POST.get('text')
            
            if user in room.discussion_users.all():
                if text != '':
                    ChatText.objects.create(
                        room = book,
                        user = user,
                        text = text
                    )

                else:
                    messages.warning(request, 'Sorry you can\'t write empty message')
                    return redirect('chat:room', room)
            else:   
                room.discussion_users.add(user)




    context = {
        'room': room,
        'texts': texts
    }

    return render(request, 'chat/rooms.html', context)



#Get object which discusstion room's timer out
def start_is_true_view(request):
    if request.method == 'GET':
        book_name = request.GET.get('book_name')
        discuss = DiscussBook.objects.get(book__name = book_name)
        discuss.is_start = True
        discuss.save()
        


        return JsonResponse({'data': 'Saved!!'})







#get when will start disscuss time

def start_discuss(request):
    
    user = request.user
    if request.method == 'GET':
        book = request.GET.get('book_name')
        time = request.GET.get('time')
        date = request.GET.get('date')
        discussbook = DiscussBook.objects.filter(owner=user, book__name = book).first()

        y, m, day = date.split('-')
        h, minut = time.split(':')
         
        day_get = day if day[0] != '0' else day[-1]
        months = m if m[0] !='0' else m[-1]
        get_date = datetime.datetime(year=int(y), month=int(months), day=int(day_get), hour=int(h), minute=int(minut))

        discuss_models = Discuss.objects.filter(book__name = book).first()
        
        # When user add time when to start discuss so we gonna is_seen also add is True in Notifications

        noti_is_seen = Notification.objects.filter(sender = user, receiver = user, book__name = book, notification_types = 5).first()
        
        for user in discuss_models.users.all():
            discussbook.discussion_users.add(user)

        discussbook.when = get_date
        discussbook.is_ready = True
        discussbook.save()


        noti_is_seen.is_seen = True
        noti_is_seen.save()
        
        return JsonResponse({'data': 'saved'})




#Create for discussion room

def create_room(request):
    user = request.user

    if request.method == 'GET':
        book_pk = request.GET.get('book_pk')
        count = request.GET.get('count')
        book = Book.objects.get(pk = book_pk)
        

        discussbook = DiscussBook.objects.filter(owner = user, book = book)
        if not discussbook.exists():
            dis_book = DiscussBook.objects.create(
                owner = user,
                book = book
            )
            #Notifications process
            noti, created = Notification.objects.get_or_create(sender = user, receiver = user, book = book, notification_types = 5)
            noti.message_text = 'You created room so you need to add time when you gonna start to discuss!!'
            noti.save()

            


        return JsonResponse({'data': 'Succesfully created!'})








@csrf_exempt
def get_message_from_js(request):
    user = request.user
    if request.method == 'POST':
        username = request.POST.get('name')
        text = request.POST.get('text')
        receiver = Account.objects.get(username = username)
        ChatOnetoOne.objects.create(
            user = request.user,
            sender = request.user,
            receiver = receiver,
            body = text
        )
        
        return JsonResponse({'data': 'Data saved'})

    else:
        return JsonResponse({'data': 'data Not saved'})





def send_message_view(request):
    user = request.user

    if request.method == 'POST':
        receiver_pk = request.POST.get('receiver')
        text = request.POST.get('text') or None
        account = Account.objects.get(pk = receiver_pk)
     
        if text is not None:
            ChatOnetoOne.objects.create(
                user = user,
                sender = user,
                receiver = account,
                body = text
            )

     

        else:
            messages.error(request, "You can't send an empty message!!")
            return redirect('myaccount:my-account', receiver_pk)



        return redirect('myaccount:my-account', receiver_pk)

chat/templates/chat/close.html
{% extends 'base.html' %}


{% block content %}


<h3 class="mt-3 font-monospace">
    Are you sure close this discussion Room?
</h3>
<form action="" method="post">
    {% csrf_token %}
    <p class="text-danger font-monospace">CLose {{ room.book.name }} room.</p>
    <button type="submit" class="btn btn-outline-danger">Close</button>
    <a class="btn btn-outline-success ms-3" href="{% url 'chat:room' room.book.name %}">Cancel</a>
</form>


{% endblock content %}

chat/templates/chat/rooms.html
{% extends 'base.html' %}


{% block content %}
<style>
    .book_image{
        width: 100px;
        height: 100px;
        object-fit: cover;
        border-radius: 8px;
        border: 1px solid skyblue;
    }

    .user_profile_image{
        width: 50px;
        height: 50px;
        border-radius: 50%;
        object-fit: cover;
    }
    .user_username{
        font-size: 13px;
        font-weight: 700;
        color: #007185;
    }
    .text_time{
        font-size: 12px;
        font-weight: 700;
        color: #007185;
    }
    .text_text{
        font-size: 14px;
        font-weight: 700;
    }
    .bordergo{
        padding: 10px;
        border-radius: 16px;
        background-color: antiquewhite;
       
    }
    .borderyea{
        max-height: 300px;
        overflow: auto;
    }
    .box{
        margin-top: 100px;
    }
    
</style>



<div class="row mt-3 ">
    <div class="col-sm-4 text-center">
        <img class="book_image" src="{{ room.book.image.url}}" alt="{{ room.book.name }}">
        <p class="font-monospace">{{ room.book.name}}</p>
        {% if request.user == room.owner %}
            <a href="{% url 'chat:close' room.book.name %}" class="btn btn-outline-primary mb-3">Close Chat room</a>
        {% endif %}
        {% for user in room.discussion_users.all %}
                <div class="d-flex mb-2">
                    <img class="user_profile_image" src="{{ user.profile_img.url }}" alt="{{ user.username }}">
                    <p class="user_username font-monospace">@{{user.username}}</p>
                </div>
        {% endfor %}

    </div>
    <div class="col-md-8">
        <div class="">
            <div class="borderyea">
                {% for text in texts %}
                <p class="bordergo">
                    <img class="user_profile_image" src="{{ text.user.profile_img.url }}" alt="{{ text.user.username }}">
                    <span class="text_text">{{ text.text}}</span>
                    <span class="text_time">{{ text.created|timesince}} ago</span>
                </p>
                {% endfor %}
            </div>
            <form action="" method="post">
                {% csrf_token %}
                <textarea name="text" class="form-control" placeholder="Type something ..." id="" cols="50" rows="3"></textarea>
                <button type="submit" class="btn btn-dark mt-2">Send</button>
            </form>
        </div>
    </div>
</div>

<div class="box"></div>


{% endblock content %}