account/urls.py
from django.urls import path
from .views import (
    register_view,
    login_view,
    logout_view

)


app_name = 'account'

urlpatterns = [
    path('register/', register_view, name = 'register'),
    path('login/', login_view, name = 'login'),
    path('logout/', logout_view, name = 'logout'),



    
]

book/urls.py
from django.urls import path
from .views import (
    book_detail_view,
    delete_book_view,
    star_rating_view,
    add_book,
    update_book_function,
    delete_book_view,
)


app_name = 'book'

urlpatterns = [
    path('<int:pk>/', book_detail_view, name = 'detail'),
    path('rating', star_rating_view, name = 'rating'),
    path('add-book/', add_book, name = 'add-book'),
    path('update/<book>/', update_book_function, name = 'update'),
    path('delete/<book>/', delete_book_view, name = 'delete'),
    

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.urls import re_path as url

urlpatterns = [
    #url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),

    path('admin/', admin.site.urls),
    #url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),

    path('', include('personal.urls')),
    path('account/', include('account.urls')),
    path('my-account/', include('myaccount.urls')),
    path('notification/', include('notification.urls')),
    path('book/', include('book.urls')),
    path('likeordislike/', include('likeordislike.urls')),
    path('aboutbook/', include('aboutbook.urls')),
    path('comment/', include('comment.urls')),
    path('question/', include('question.urls')),
    path('chat/', include('chat.urls')),
    
    
]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    #urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

myaccount/urls.py
from django.urls import path
from .views import (
    my_account_view,
    edit_my_account_view,
    follow_view,
    save_book,

)

app_name = 'myaccount'


urlpatterns = [
    path('<int:pk>/', my_account_view, name = 'my-account'),
    path('<int:pk>/edit/',edit_my_account_view, name = 'edit'),
    path('<int:pk>/follow/',follow_view, name = 'follow'),
    path('save/<user>/<book>/', save_book, name = 'save'),

]

notification/urls.py
from django.urls import path
from .views import (
    notification_view,



)

app_name = 'notification'
urlpatterns = [
    path('<int:pk>/', notification_view, name = 'notification-view'),

]

templates/active_users.html
<div class="card p-2">
    <p class="text-center active_users">Active users</p>
    {% for active in active_users %}
    <a href="{% url 'myaccount:my-account' active.pk%}" class="profile mb-3">
        <img src="{{ active.profile_img.url}}" class="book_of_owner_image" alt="{{ active.username}}">
        <span>@{{ active.username}}</span>
    </a>
            
    {% endfor %}


</div>

templates/all_books.html
<div class="list-group d-md-block d-none">
    <a href="{% url 'home' %}?q=all" class="list-group-item list-group-item-action active" aria-current="true">
      All Books
    </a>
    {% for tag in tags %}
    <div class="d-flex justify-content-between align-items-start list-group-item">
        <a href="{% url 'home' %}?q={{ tag.title }}" class="text-decoration-none book_of_name">{{ tag.title }}</a>
        <span class="badge bg-primary rounded-pill">{{ tag.nums_of_book }}</span>
    </div>
    {% endfor %}
</div>

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Social Book</title>
    {% block title %} {% endblock %}
    <!-- Bootstrap css -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer">

    <!-- Jquery -->
    <script src="https://code.jquery.com/jquery-3.6.1.min.js" integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>
    <!-- Cropper -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/cropper/4.1.0/cropper.min.js" integrity="sha512-E+gDQcIvNXE60SjCS38ysf1mGh4ObBpKcUOp0oEaHQHQAdaN2p7GelOpgEdpTuCLoIJyLkNXiqFZbyD9Ak/Ygw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/cropper/4.1.0/cropper.css" integrity="sha512-iAcZ4OrGhQ7KDqtM+LMc+iuv63aJ9O7hPyWBzCXsrZYuhJ6jhdeh40+hf9o4QmZVu8QrH/cWy/JTmoKNOL4Urw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    


  
  </head>
  <body>
    {% include 'base_style.html'%}

    {% include 'header.html'%}

    <!-- Messages  -->
    {% if messages %}
  
        {% for message in messages %}
        <div class="alert alert-{% if message.tags == 'error' %}danger {% else %}{{ message.tags }} {% endif %}alert-dismissible fade show" role="alert">
          <strong>{{ message }}</strong> 
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}

    {% endif %}

    <!-- // messages -->

    <div class="container">
        {% block content %}

        {% endblock content %}
    </div>

    {% include 'footer.html'%}
    
    

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
  </body>
</html>

templates/base_style.html
<style>
    *{
        margin: 0;
        padding: 0;
    }

    body{
        font-family: sans-serif;
        background-color: #f2f2f2;
    }







</style>

templates/feed_books.html
{% load static %}
<div class="row g-3 justify-content-md-center">
    {% for book in books %}
    <div class="p-2 me-1 col-lg-5 col-md-10 col-sm-12 card shadow">
        <img  src="{{ book.image.url }}" class="rounded card-img-top book-image  img-thumbnail" alt="{{ book.name }}">
        <div class="card-body">
            <a href="{% url 'book:detail' book.pk %}" class="text-decoration-none book_of_name">
                <h6 class="card-title text-center"><strong>{{ book.name }}</strong></h6>
            </a>
            
            <!-- Star Rating -->

            {% if book.get_percentage_of_star == 0 %}
            <div class="dropdown">
                <button class="book_of_name dropdown_btn dropdown-toggle"  data-bs-toggle="dropdown" aria-expanded="false">
                    <img src="{% static '0-rating.png'%}" class="rating-img" alt="rating">
                    <span class="ms-2 fs-6">{{ book.get_users_of_star }}</span>
                </button>
                <div class="dropdown-menu menu p-3">
                    <h6 class="time-book"><img src="{% static '0-rating.png'%}" class="rating-img_2" alt="rating">0 out of 5</h6>
                    <h4 class="global_rating">0 global ratings</h4>
                    <div>
                        <a class="dropdown-item d-flex justify-content-between" href="#">
                            <span>5 star</span>
                            <div class="parent_back" >
                               
                            </div>
                            <span>0 %</span>
                        </a>
                        <a class="dropdown-item d-flex justify-content-between" href="#">
                            <span>4 star</span>
                            <div class="parent_back">
                                
                            </div>
                            <span>0 %</span>
                        </a>
                        <a class="dropdown-item d-flex justify-content-between" href="#">
                            <span>3 star</span>
                            <div class="parent_back">
                              
                            </div>
                            <span>0 %</span>
                        </a>
                        <a class="dropdown-item d-flex justify-content-between" href="#">
                            <span>2 star</span>
                            <div class="parent_back">
                            
                            </div>
                            <span>0 %</span>
                        </a>
                        <a class="dropdown-item d-flex justify-content-between" href="#">
                            <span>1 star</span>
                            <div class="parent_back">

                            </div>
                            <span>0 %</span>
                        </a>
                    </div>
                    
                </div>
            </div>
            

            {% elif book.get_percentage_of_star < 10 %}
                <div class="dropdown">
                    <button class="book_of_name dropdown_btn dropdown-toggle"  data-bs-toggle="dropdown" aria-expanded="false">
                        {% if book.get_percentage_of_star < 2 %}
                            <img src="{% static '0.5-rating.png'%}" class="rating-img" alt="rating">
                        {% elif book.get_percentage_of_star < 3%}
                            <img src="{% static '2.5-rating.png'%}" class="rating-img" alt="rating">
                        {% elif book.get_percentage_of_star < 4 %}
                            <img src="{% static '3.5-rating.png'%}" class="rating-img" alt="rating">
                        {% elif book.get_percentage_of_star < 5 %}
                            <img src="{% static '4.5-rating.png'%}" class="rating-img" alt="rating">
                        {% endif %}
                        
                        <span class="ms-2 fs-6">{{ book.get_users_of_star }}</span>
                    </button>
                    <div class="dropdown-menu menu p-3">
                        <h6 class="time-book"><img src="{% static '0.5-rating.png'%}" class="rating-img_2" alt="rating">{{ book.get_percentage_of_star}} out of 5</h6>
                        <h4 class="global_rating">{{ book.get_users_of_star}} global ratings </h4>
                        <div>
                            <!-- FIVE STAR -->
                            <a class="dropdown-item d-flex justify-content-between" href="#">
                                <span>5 star</span>
                                <div class="parent_back" >
                                    <div class="child_back" style="width:{{ book.get_five_of_star_for_style_width }}%;" |safe>
                                        {% if book.get_five_of_star == 0 %}  {% else %} i {% endif %}
                                    </div>
                                </div>
                                <span>{{ book.get_five_of_star }}%</span>
                            </a>
                            <!-- END FIVE STAR -->

                            <!-- FOUR STAR -->
                            <a class="dropdown-item d-flex justify-content-between" href="#">
                                <span>4 star</span>
                                <div class="parent_back">
                                    <div class="child_back" style="width: {{ book.get_four_of_star_for_style_width}}%;" |safe >
                                        {% if book.get_four_of_star == 0 %}  {% else %} i {% endif %}
                                    </div>
                                </div>
                                <span>{{ book.get_four_of_star }}%</span>
                            </a>
                            <!-- END FOUR STAR -->

                            <!-- THREE STAR -->
                            <a class="dropdown-item d-flex justify-content-between" href="#">
                                <span>3 star</span>
                                <div class="parent_back">
                                    <div class="child_back" style="width: {{ book.get_three_of_star_for_style_width }}%;" |safe>
                                        {% if book.get_three_of_star == 0 %}  {% else %} i {% endif %}
                                    </div>
                                </div>
                                <span>{{ book.get_three_of_star }}%</span>
                            </a>
                            <!-- END THREE STAR -->

                            <!-- TWO STAR -->
                            <a class="dropdown-item d-flex justify-content-between" href="#">
                                <span>2 star</span>
                                <div class="parent_back">
                                    <div class="child_back" style="width: {{ book.get_two_of_star_for_style_width }}%;" |safe>
                                        {% if book.get_two_of_star  == 0 %}  {% else %} i {% endif %}
                                    </div>
                                </div>
                                <span>{{ book.get_two_of_star }}%</span>
                            </a>
                            <!-- END TWO STAR -->
                            
                            <!-- ONE STAR  -->
                            <a class="dropdown-item d-flex justify-content-between" href="#">
                                <span>1 star</span>
                                <div class="parent_back">
                                    <div class="child_back" style="width: {{ book.get_one_of_star_for_style_width }}%;" |safe>
                                        {% if book.get_one_of_star == 0 %}  {% else %} i {% endif %}
                                    </div>
                                </div>
                                <span>{{ book.get_one_of_star }}%</span>
                            </a>
                            <!-- END ONE STAR  -->
                        </div>
                        
                    </div>
                </div>
                
            {% endif %}



            <!-- /Star Rating -->
            
            
                <blockquote class="blockquote mb-0">
                    <div class="d-flex justify-content-between align-items-center">
                        <a href="{% url 'myaccount:my-account' book.owner.pk%}" class="profile">
                            {% if book.owner.profile_img %}
                                <img src="{{ book.owner.profile_img.url}}" class="book_of_owner_image" alt="{{ book.owner.username}}">
                            {% endif %}
                            <span >@{{ book.owner.username}}</span>
                        </a>
                        <small class="time-book">
                            {{book.created|timesince}} ago
                        </small>
                    
                    </div>
                    <footer class="blockquote-footer mt-3"><cite title="Source Title">{{ book.feedback }}</cite></footer>
                </blockquote>
            
        </div>
        <div class="card-footer d-flex justify-content-around">
            <div class="">
                <a href="{% url 'download_as_pdf' book.name %}" class="book_of_footer me-3"><i class="fa-solid fa-download fs-5"></i></a>
                <p class="icons">download</p>
            </div>
            <!-- <div>
                <a href="" class="book_of_footer me-3"><i class="fa-solid fa-share fs-5"></i></a>
                <p class="icons">share</p>
            </div> -->
            <div>
                
                <a href="{% url 'myaccount:save' request.user book.name%}" class="book_of_footer me-3"><i class="fa-regular fa-bookmark fs-5"></i></a>
                <p class="icons">save</p>
               
              
            </div>
         
            <div>
                <a href="#" class="book_of_footer me-3"><i class="fa-regular fa-eye fs-5"></i></a>
                <p class="icons">{% if book.count_views > 1%} views {% else %} view {% endif %} {{ book.count_views}}</p>
            </div>
        </div>
    </div>

    {% empty %}
        <h3>No Books</h3>
    {% endfor %}
</div>

templates/footer.html
<footer class="page-footer mt-5 font-small indigo fixed-bottom opacity-0.5 bg-info">
    <div class="footer-copyright text-center py-4 text-white">&copy; 2022 Copyright
        <a href="{% url 'home' %}" class="text-white">My Social Book</a>
    </div>
</footer>

templates/header.html
<!-- Media screens -->

<div class=" d-flex p-3 bg-white border-bottom shadow  px-md-4">

    <div class="d-none d-md-flex flex-row my-auto flex-grow-1 align-items-center">
        <h5 class="justify-content-center">
            <a href="{% url 'home'%}" class="text-dark p-2">My Social <span class="text-warning">Book</span><i class="mx-2 fa-solid fa-book text-info fs-3"></i></a>
        </h5>
        <!-- Column2 -->
        <form action="{% url 'search'%}" method="get" class="justify-content-center mx-3">
            <input type="text" class="form-control" name="q" placeholder="Search Book....">
        </form>
        <!-- Column3 -->
        <!-- Notifications process -->
        {% if request.user.is_authenticated %}
        <div class="d-flex ms-5 flex-row-reverse flex-grow-2">
          
          <a class=" position-relative" href="{% url 'notification:notification-view' request.user.pk%}">
            <i class="fa-regular fa-bell fs-3"></i>
            <span class="position-absolute top-0 ms-1 start-100 translate-middle badge rounded-pill bg-danger">
              {% if noti %}
                {{ how_may }}
              {% else %}
              0
              {% endif %}
              <span class="visually-hidden">unread messages</span>
            </span>
          </a>
        </div>
        {% else %}
        <div class="d-flex ms-5 flex-row-reverse flex-grow-2">
          
          <a class=" position-relative" href="">
            <i class="fa-regular fa-bell fs-3"></i>
            <span class="position-absolute top-0 ms-1 start-100 translate-middle badge rounded-pill bg-danger">
              0
              <span class="visually-hidden">unread messages</span>
            </span>
          </a>
        </div>
        {% endif %}
        <!-- / notification -->


        <div class="d-flex flex-row-reverse flex-grow-1 me-4">
          
            {% if request.user.is_authenticated %}
            <div class="dropdown">
                <button class="rounded-circle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                    {% if request.user.profile_img %}
                    <img src="{{ request.user.profile_img.url }}" width="60" height="60" style="border-radius: 50%;" alt="{{ request.user.username }}">
                    {% endif %}
                </button>
                <ul class="dropdown-menu dropdown-menu-dark">
                  <li>
                    <a href="{% url 'myaccount:my-account' request.user.pk %}" class="dropdown-item active p-2">My Account</a>
                  </li>
                  <li>
                    <a href="{% url 'account:logout'%}" class="dropdown-item">Logout</a>
                  </li>
                </ul>
            </div>
            {% else %}

            <div class="dropdown me-4">
              <button class="btn btn-warning rounded-circle fs-4" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                <i class="fa-solid fa-user "></i>
              </button>
              <ul class="dropdown-menu dropdown-menu-dark">
                <li><a class="dropdown-item active" href="{% url 'account:login' %}">Login</a></li>
                <li><a class="dropdown-item" href="{% url 'account:register' %}">Dizimnen o'tiw</a></li>               
              </ul>
            </div>
            {% endif %}
        </div>
    </div>


    <!-- small screen -->

    <div class="d-flex d-md-none flex-column mx-auto align-items-center">
        <h5 class="font-weight-normal mb-sm-3 ">
            <a href="{% url 'home'%}" class="text-dark p-2">My Social <span class="text-warning">Book</span><i class="mx-2 fa-solid fa-book text-info fs-3"></i></a>
        </h5>
        <!-- column2 -->
        <div class="col-sm-10 d-flex">
          <form action="{% url 'search' %}" class="justify-content-center" >
            <input type="text" class="form-control" name="q" placeholder="Search..." id="id_search_small">
        </form>

        <!-- Notifications process -->
      <div class="ms-4">
            {% if request.user.is_authenticated %}
              <a class="position-relative" href="{% url 'notification:notification-view' request.user.pk%}">
                <i class="fa-regular fa-bell fs-3"></i>
                <span class="position-absolute top-0 ms-1 start-100 translate-middle badge rounded-pill bg-danger">
                  {% if noti %}
                    {{ how_may }}
                  {% else %}
                  0
                  {% endif %}
                  <span class="visually-hidden">unread messages</span>
                </span>
              </a>
            {% else %}

              <a class="position-relative" href="">
                <i class="fa-regular fa-bell fs-3"></i>
                <span class="position-absolute top-0 ms-1 start-100 translate-middle badge rounded-pill bg-danger">
                  0
                  <span class="visually-hidden">unread messages</span>
                </span>
              </a>
          
            {% endif %}
            <!-- / notification -->
            </div>
      </div>



        <div class="d-flex flex-column mt-4">
            {% if request.user.is_authenticated %}

            <div class="dropdown">
                <button class="rounded-circle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <img src="{{ request.user.profile_img.url }}" width="60" height="60" style="border-radius: 50%;" alt="">
                </button>
                <ul class="dropdown-menu dropdown-menu-dark">
                  <li>
                    <a href="{% url 'myaccount:my-account' request.user.pk %}" class="dropdown-item active p-2">My Account</a>
                  </li>
                  <li>
                    <a href="{% url 'account:logout'%}" class="dropdown-item">Logout</a>
                  </li>
                </ul>
              </div>

            {% else %}
            <a href="{% url 'account:login'%}" class="p-2 btn btn-outline-success mb-3">Login</a>
            <a href="{% url 'account:register'%}" class="btn btn-outline-primary">Dizimnen otiw</a>

            {% endif %}

        </div>

    </div>

</div>

templates/search.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<style>
    .book_of_owner_image{
        width: 35px;
        height: 35px;
        border-radius: 50%;
    }
    .profile{
        text-decoration: none;
        color: #007185;
        font-size: 13px;
        font-weight: 700;
    }
    .profile:hover{
        color: #c7511f;
    }
    .book_of_name{
        color: #007185;
    }
    .book_of_name:hover{
        color: #c7511f;
    }
    .book_of_footer{
        color: #007185;
    }

    .time-book{
        font-size: 12px;
        color: #0f1111;
        font-weight: 600;
    }
    .active_users{
        font-size: 16px;
        font-weight: 700;
        color: #565959;
    }
    .icons{
        font-size: 14px;
        font-weight: 700;
    }
    .rating-img{
        width: 150px;
    }
    .rating-img_2{
        width: 100px;
    }

    .dropdown_btn{
        border: none;
        background-color: inherit;
    }

    .global_rating{
        color: #007185;
        font-size: 16px;
        font-weight: 700;
    }

    .menu{
        width: 300px;
    }
    .parent_back{
        border: 1px solid #007185;
        width: 100%;
        margin: 0 10px;
        border-radius: 5px;
    }
    .child_back{
        background-color: yellow;
        color: yellow;
    }
    .give_me_margin{
        margin-bottom: 100px;
    }


 
    
</style>

    <!-- for tags small screen -->
    <div class="d-sm-block d-md-none ms-4">
        <a href="{% url 'home' %}?q=all" class="profile pe-3">
            Barliq kitaplar
        </a>
        {% for tag in tags %}
            <a href="{% url 'home' %}?q={{ tag.title }}" class="profile pe-3">{{ tag.title }} <span class="badge bg-primary">{{ tag.count_book }}</span></a>
        {% endfor %}
    </div>

<!-- // small screen -->

<div class="row mt-3">
    <div class="col-md-3">
        {% include 'all_books.html'%}
    </div>
    <div class="col-sm-8 col-md-7">

        {% include 'feed_books.html'%}

    </div>

    <div class="col-md-2 col-sm-4 ">
        {% include 'active_users.html'%}
        
    </div>

    

</div>

<div class="give_me_margin"></div>





{% endblock content %}